[project]
name = "turning-point-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.110.0",
    "httpx>=0.28.1",
    "mcp>=2.0.0",
    "numpy>=2.5.2",
    "openai>=3.2.0",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.29.0",
]
